ice-lab/ice-next

examples/basic-project/src/pages/home.tsx
packages/ice/template/index.ts.ejs
packages/plugin-auth/runtime/Auth.tsx
packages/plugin-auth/runtime/index.tsx
packages/plugin-router/runtime/index.tsx
packages/runtime/package.json
packages/runtime/src/App.tsx
packages/runtime/src/AppContext.tsx
packages/runtime/src/AppRouter.tsx
packages/runtime/src/RouteItem.tsx
packages/runtime/src/index.ts
packages/runtime/src/render.tsx
packages/runtime/src/runApp.tsx
packages/runtime/src/runtime.tsx
packages/runtime/src/types.ts
pnpm-lock.yaml

- 合并 context + appConfig -> appContext
- 提供 useAppContext API
- 移除 runtime 的 setRenderApp，同时提供 set&getAppRouter API

feat: useAppContext

---

tests/integration/basic-project.test.ts
tests/utils/browser.ts

update API for `page.$$attr` and `page.$attr`

fix: test utils of puppeteer page

---

packages/runtime/src/routes.tsx

Closed: https://github.com/ice-lab/ice-next/issues/82

fix: fail to load latest module in ssr

---

examples/basic-project/package.json
examples/routes-generate/package.json
package.json
packages/ice/bin/ice-cli.mjs
packages/ice/package.json
packages/plugin-auth/package.json
packages/runtime/package.json
packages/runtime/src/AppErrorBoundary.tsx
packages/runtime/src/runClientApp.tsx
packages/runtime/src/runServerApp.tsx
packages/runtime/src/runtime.tsx
packages/runtime/src/types.ts
packages/types/package.json
pnpm-lock.yaml
website/package.json

feat: upgrade to react 18

---

packages/bundles/tasks.ts

fix: utils not found

---

packages/ice/src/plugins/config.ts
packages/webpack-config/src/index.ts

fix: userConfig of minify

---

packages/bundles/package.json
packages/ice/package.json
packages/ice/src/plugins/web/index.ts
packages/types/package.json
packages/webpack-config/package.json
pnpm-lock.yaml

fix: errors when publish

---

packages/runtime/src/Document.tsx
packages/webpack-config/src/webpackPlugins/AssetsManifestPlugin.ts

fix: hmr failed when reload

---

packages/runtime/package.json
packages/runtime/src/jsx-dev-runtime.ts

fix: add jsx dev runtime

---

packages/types/src/config.ts
packages/webpack-config/src/index.ts

支持在插件中修改 webpack 插件。For example:
```ts
onGetConfig((config) => {
config.plugins = ['xxx'];
return config;
})
```

feat: support modify webpack plugins

---

.github/workflows/auto-publisher.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/website.yml
package.json
pnpm-lock.yaml
vitest.config.ts

feat: ci coverage

---

packages/ice/src/tasks/web/data-loader.ts
packages/webpack-config/src/index.ts

fix: remove hmr for data-loader

---

packages/types/src/plugin.ts
packages/types/src/userConfig.ts

Closed: https://github.com/ice-lab/ice-next/issues/285

fix: userConfig plugins types

---

examples/basic-project/ice.config.mts
packages/ice/src/config.ts
packages/types/src/userConfig.ts
website/docs/guide/basic/config.md

feat: config transform

---

packages/plugin-pha/src/manifestHelpers.ts

Fix options of renderHTML set `documentOnly: true` and `renderMode: 'SSG'`

fix: options of renderHTML

---

packages/ice/package.json
pnpm-lock.yaml

Close: https://github.com/ice-lab/ice-next/issues/312

fix: deprecate multer package version

---

packages/ice/src/config.ts

add default value of publicPath and devPublicPath

chore: add default value of publicPath

---

packages/ice/src/service/serverCompiler.ts

feat: support pass external value to esbuild

---

examples/rax-project/src/document.tsx
packages/ice/src/service/serverCompiler.ts
packages/webpack-config/package.json
pnpm-lock.yaml

- merge swc options from task config while it may modified by plugins
- lock version of `@swc/core`

fix: merge swc options for sever compiler

---

packages/ice/src/commands/build.ts

Keep server content when SSR is enabled.

fix: ssr bundle error when ssg is false

---

packages/ice/src/commands/build.ts
packages/ice/src/commands/start.ts
packages/ice/src/service/serverCompiler.ts
packages/ice/src/utils/getServerEntry.ts
packages/types/src/config.ts

支持自定义 server 入口：
1. 新建 src/entry.server.ts 文件
2. 在插件中通过 config.server.entry 指定 server 入口绝对地址

feat: support custom server entry

---

packages/ice/templates/entry.server.ts.ejs

fix: disableFallback param not pass

---

packages/webpack-config/src/getCompilerPlugins.ts
packages/webpack-config/src/unPlugins/compilation.ts

fix: cache root for swc plugin

---

packages/ice/src/commands/build.ts
packages/ice/src/commands/start.ts
packages/ice/src/esbuild/depRedirect.ts
packages/ice/src/esbuild/transformPipe.ts
packages/ice/src/service/serverCompiler.ts
packages/types/src/config.ts
packages/webpack-config/src/getCompilerPlugins.ts

refactor `esbuild` plugins when it has transform lifecycle

feat: add transform pipe for esbuild plugin

---

website/src/theme/Root.js
website/src/utils/internal.js

Site xiaomi

---

packages/ice/src/service/webpackCompiler.ts

- fix white underline of dev url
- fix dev url when open browser

fix: dev url when open browser

---

packages/ice/src/commands/start.ts
packages/ice/src/service/config.ts
packages/ice/src/webpack/ReCompilePlugin.ts

Fix parallel tasks like getAppConfig with different config

fix: add task map for parallel tasks with different config

---

packages/ice/package.json

update node engines to 14.19.0

fix: node engines

---

packages/ice/src/service/config.ts

fix: bind reCompile scope

---

examples/with-pha/src/pages/home.tsx
packages/ice/src/service/config.ts

get default value from routes config

fix: get default value form routes config

---

.github/workflows/auto-publisher.yml
package.json
packages/plugin-antd/package.json
packages/style-import/package.json

auto publish ci for release tag when merge master

chore: ci workflow for release

---

examples/with-store/src/models/user.ts
examples/with-store/src/pages/blog/models/info.ts
examples/with-store/src/pages/blog/store.ts
examples/with-store/src/pages/models/counter.ts
examples/with-store/src/pages/store.ts
examples/with-store/src/store.ts
packages/plugin-store/src/index.ts

feat: export createStore and createModel api from ice

---

packages/style-import/tests/importStyle.test.ts

https://github.com/ice-lab/ice-next/runs/7945883534?check_suite_focus=true
改动关联的 PR：https://github.com/ice-lab/ice-next/pull/469

fix: importStyle test case

---

examples/basic-project/src/app.tsx
examples/basic-project/src/pages/about.tsx
packages/ice/templates/core/index.ts.ejs
packages/runtime/src/history.ts
packages/runtime/src/index.ts
packages/runtime/src/runClientApp.tsx

feat: support import history from ice

---

examples/with-fusion/src/pages/index.tsx
packages/webpack-config/src/config/splitChunks.ts

fix: import css from node_modules

---

packages/plugin-fusion/src/index.ts

fix: add semicolon for style import

---

packages/ice/src/service/config.ts

Fix: add package version for cache key

---

packages/runtime/src/Document.tsx
packages/runtime/src/types.ts
packages/webpack-config/src/webpackPlugins/AssetsManifestPlugin.ts

fix https://github.com/ice-lab/ice-next/issues/459 中的问题1

fix: assets order

---

examples/basic-project/package.json
examples/csr-project/package.json
examples/rax-project/package.json
examples/routes-generate/package.json
examples/single-route/package.json
examples/with-antd-mobile/package.json
examples/with-antd/package.json
examples/with-pha/package.json
examples/with-store/package.json
pnpm-lock.yaml

Remove unnecessary dependency of `browserslist`

chore: remove unnecessary devDependencies

---

packages/plugin-fusion/src/index.ts

Do not import theme icon in every scss file.

fix: import theme icon

---

examples/rax-project/ice.config.mts
packages/ice/src/service/analyze.ts
packages/ice/src/service/preBundleCJSDeps.ts
packages/ice/src/service/serverCompiler.ts
packages/ice/tests/preBundleCJSDeps.test.ts
packages/ice/tests/transformImport.test.ts
packages/types/src/config.ts
packages/webpack-config/src/index.ts
tests/integration/rax-project.test.ts

https://github.com/ice-lab/ice-next/issues/441

fix: rax project ssr failed

---

packages/ice/src/utils/getRouterBasename.ts
packages/ice/templates/core/entry.client.ts.ejs
packages/ice/templates/core/entry.server.ts.ejs

考虑到接入自定义域名的情况，需要调整 basename 的顺序，以用户设定的 basename 优先级最高

fix: basename order

---

examples/basic-project/ice.config.mts
packages/ice/src/config.ts
packages/ice/src/tasks/web/index.ts
packages/types/src/config.ts
packages/types/src/userConfig.ts
packages/webpack-config/src/index.ts

Minify of swc is still experimental, config `minify: 'swc'` for faster minification.

feat: support swc minification

---

examples/basic-project/ice.config.mts
examples/basic-project/plugin.ts
packages/ice/src/esbuild/transformPipe.ts
packages/types/src/config.ts
packages/webpack-config/src/getCompilerPlugins.ts

feat: enhance transform plugins

---

packages/runtime/src/Document.tsx
packages/runtime/src/routesConfig.ts

- add types for document component
- block 相关能力未实现，暂时移除 @chenjun1011 
Close #419

feat: add types for document component

---

examples/with-store/ice.config.mts
packages/plugin-store/src/index.ts

https://github.com/ice-lab/ice-next/issues/395#issuecomment-1211502181

chore: change disableResetPageState to resetPageState

---

examples/basic-project/src/app.tsx
packages/plugin-auth/CHANGELOG.md
packages/plugin-auth/src/runtime/index.tsx
packages/plugin-auth/src/types.ts

support initialize auth by app data.

feat: support initialize auth by app data

---

packages/webpack-modify/CHANGELOG.md
packages/webpack-modify/README.md
packages/webpack-modify/package.json
packages/webpack-modify/src/index.ts
packages/webpack-modify/tests/api.test.ts
pnpm-lock.yaml

feat: support several APIs to modify webpack

---

packages/webpack-modify/src/index.ts
packages/webpack-modify/tsconfig.json

Add tsconfig.json and fix type error

chore: add tsconfig for @ice/webpack-modify

---

packages/ice/templates/core/404.tsx

chore: remove default 404 page

---

website/docs/guide/basic/app.md

docs: memory router

---

examples/basic-project/src/components/bar.tsx
packages/ice/src/esbuild/ignore.ts
packages/ice/tests/fixtures/ignore/app.ts
packages/ice/tests/fixtures/ignore/dir/ignored.ts
packages/ice/tests/fixtures/ignore/dir/nested/content.ts
packages/ice/tests/fixtures/ignore/dir/page.ts
packages/ice/tests/ignore.test.ts
tests/integration/basic-project.test.ts

Return args.path will case error of non-absolute path resolve

fix: ignore with non-absoulte path

---

packages/ice/src/test/defineVitestConfig.ts
packages/ice/tests/defineJestConfig.test.ts
packages/ice/tests/defineVitestConfig.test.ts

Closed: https://github.com/ice-lab/ice-next/issues/549

test: add defineJestConfig and defineVitestConfig test cases

---

packages/webpack-config/src/config/css.ts

fix: css chunk filename 

---

packages/runtime/src/Document.tsx
packages/runtime/src/runClientApp.tsx
packages/runtime/tests/runServerApp.test.tsx
packages/types/src/runtime.ts
packages/webpack-config/src/webpackPlugins/AssetsManifestPlugin.ts

Remove `assetsManifest` from html and inject it to entry file.

fix: optimize html output

---

scripts/publishPackage.ts

feat: add sync command log

---

website/docs/guide/basic/development.md

docs: optimize development docs

---

packages/ice/src/utils/babelPluginRemoveCode.ts
packages/ice/tests/fixtures/removeCode/mixed-import.tsx
packages/ice/tests/removeTopLevelCode.test.ts

fix: error occurs when remove unused code

---

packages/webpack-config/src/unPlugins/compilation.ts

现在的问题是在 webpack 构建流程中，this 是不存在，error 都没有打印出来。

fix: log error stack when transform error

---

packages/runtime/src/dataLoader.ts

chore: modify name of loaders

---

packages/runtime/src/Document.tsx
packages/runtime/src/dataLoader.ts
packages/runtime/src/runClientApp.tsx
packages/types/src/runtime.ts

- fix: 主动降级时，也应该禁用 hydrate 
- fix: https://github.com/ice-lab/ice-next/issues/624

fix: should disable hydrate when document only

---

packages/style-import/src/index.ts

Ignore files for import transform
Close #598

fix: add transform include for non-js files

---

packages/runtime/package.json
packages/webpack-config/src/config/splitChunks.ts

fix: regex rule for different package manager

---

packages/ice/templates/exports/data-loader.ts.ejs

fix https://github.com/ice-lab/ice-next/issues/513

fix: loaders undefined

---

examples/with-web-worker/ice.config.mts
examples/with-web-worker/package.json
examples/with-web-worker/src/app.ts
examples/with-web-worker/src/document.tsx
examples/with-web-worker/src/pages/index.tsx
examples/with-web-worker/src/utils/pi.ts
examples/with-web-worker/src/worker.ts
examples/with-web-worker/tsconfig.json
pnpm-lock.yaml
website/docs/guide/basic/assets.md

feat: web-worker example

---

packages/ice/src/commands/build.ts
packages/ice/src/types/userConfig.ts

fix: webpack instance of compiled bundle

---

packages/ice/src/commands/build.ts
packages/ice/src/commands/start.ts
packages/ice/src/createService.ts
packages/webpack-config/src/index.ts

https://github.com/ice-lab/ice-next/issues/575

fix: still use cache when config is modified

---

examples/basic-project/src/app.tsx
packages/webpack-config/package.json
packages/webpack-config/src/index.ts
pnpm-lock.yaml

Fix error of undefined process in client.

fix: add process support for undefined env variables

---

packages/runtime/src/Document.tsx

- Data 组件透出全量的 AppContext，供搭建场景单独消费

feat: use app context separately

---

website/docs/guide/advanced/integrate-from-rax.md

docs: add doc of rax-migrate

---

website/docs/guide/basic/assets.md

docs: optimize assets

---

examples/basic-project/src/document.tsx
examples/basic-project/src/pages/index.tsx
examples/basic-project/src/types.ts

#665 
结论是不导出 AppData，用户在项目中自己定义 AppData 的类型

chore: add AppData type

---

examples/with-store/src/app.tsx
packages/plugin-store/src/runtime.tsx

```diff
// src/app.ts
- export const store = defineStoreConfig();
+ export const storeConfig = defineStoreConfig();
```

feat: modify store to storeConfig
