ice-lab/ice-next

- packages/ice/src/commands/build.ts
- packages/ice/src/service/webpackCompiler.ts
由于 compiler.hooks.done 是 AsyncSeriesHook，因此不支持 async 的执行逻辑，在 start 阶段不应该等待 compiler 执行结束后才返回，而 build 阶段则需要，否则导致一些 ci 流程无法保证时序
> fix: await compile hooks when build

- packages/ice/src/service/webpackCompiler.ts
- packages/plugin-app/src/index.ts
原日志过于简单
默认情况下 start 和 build 统一输出 assets 信息
> chore: assets output in build

- examples/basic-project/package.json
- examples/csr-project/package.json
- examples/routes-generate/package.json
- examples/single-route/package.json
- packages/bundles/package.json
- packages/ice/bin/ice-cli.mjs
- packages/ice/package.json
- packages/runtime/package.json
- packages/types/package.json
- pnpm-lock.yaml
`fs/promises` 只在 node 14+ 支持
ref:
- https://nodejs.org/docs/latest-v12.x/api/fs.html#fs_fs_promises_api
- https://github.com/SAP-samples/hana-developer-cli-tool-example/issues/57
一些依赖版本修改说明：
由于 pnpm 发布 7.0.0 版本，导致在执行 build 的时候报错。
- 补全了丢失的 peerDependencies
- 指定 examples 中依赖的 `@ice/*` 的包是从 workspace 中依赖的。Ref: https://pnpm.io/zh/workspaces#workspace-%E5%8D%8F%E8%AE%AE-workspace
- 补全了一些丢失的 `@types/*` 的包，避免执行 build 的时候报错
> Fix: fs/promises module not found in node12

- packages/ice/package.json
- packages/ice/src/plugins/web/ssr/serverRender.ts
- packages/runtime/package.json
- packages/runtime/src/runtime.tsx
- packages/runtime/src/types.ts
Fix: app.addProvider 设置了但未生效
额外修复两个问题：
- 调用了 `res.end()` 后，后面的逻辑仍然运行了
- 避免安装 npm 包时下载没必要的文件
> Fix: app.addProvider not be added

- packages/webpack-config/src/index.ts
目前会有这个 warning，导致 hmr 失效了: 
Ref: https://github.com/pmmmwh/react-refresh-webpack-plugin/issues/88#issuecomment-627558799
> Fix: hmr fail

- packages/ice/src/plugins/web/index.ts
- packages/ice/src/service/compile.ts
- packages/runtime/src/routes.tsx
- packages/runtime/src/runServerApp.tsx
现在为了避免 CSR 时把页面组件都加载进来导致资源（比如 css）加载报错，带来的问题是调用 renderHTML 的时候 getConfig 失效了，后面需要讨论。
如果用 esbuild 打包成一个 server bundle 时，会有以下产物：
这时候，加载 server bundle 时，就会把所有的 页面组件都加载进来了。
因此需要开启分包 （splitting: true）
> Fix: csr load component module

- packages/ice/package.json
- pnpm-lock.yaml
安装 `@ice/app` 这个包时候，`@ice/types` 这个包不会被安装，因为它是放在 devDependencies
> Fix: define config types is missing

- packages/ice/src/commands/build.ts
- packages/ice/src/constant.ts
- packages/ice/src/middlewares/ssr.ts
- packages/ice/src/service/serverCompiler.ts
- packages/ice/src/tasks/web/index.ts
- packages/types/src/plugin.ts
- packages/webpack-config/src/index.ts
一些变更点说明：
- 暂时去掉 loader entry，避免打包出重复的内容导致加载时间过长。后面需等待 https://github.com/ice-lab/ice-next/issues/217 解决
- 打包 serverEntry 暂时需要 `splitting: true` 原因详见：https://github.com/ice-lab/ice-next/pull/188 ，需等待 https://github.com/ice-lab/ice-next/issues/199 解决
> fix: webpack/hot alias

- packages/ice/src/middlewares/ssr.ts
- packages/ice/src/service/webpackCompiler.ts
- packages/webpack-config/src/index.ts
- packages/webpack-config/src/unPlugins/compilation.ts
> fix: improve compile experience

- packages/plugin-rax-compat/src/index.ts
- packages/rax-compat/src/create-element.ts
- packages/rax-compat/src/hooks.ts
1. rax-compat 修复 createElement 的 children 渲染两次的问题
2. rax-compat 修复 style 对象的 prototype 为 null 的问题
3. 限制 plugin-rax-compat 的 inlineStyle WARN 告警只提示一次
4. rax-compat 兼容 rax 的 setState 同值不重新渲染的逻辑
> fix: compat rax and warn once

- packages/ice/src/createService.ts
- packages/ice/src/tasks/web/data-loader.ts
- packages/jsx-runtime/package.json
- pnpm-lock.yaml
1. alias for `'webpack/hot': '@ice/bundles/compiled/webpack/hot',`
2. remove event dependency for webpack-config
3. add type: module for jsx-runtime
4. serverCompiler remove `jsxTransform: false`, to avoid build fail in `ice build`  Close #https://github.com/ice-lab/ice-next/issues/272
> fix: data loader task for webpack hot

- packages/bundles/package.json
- pnpm-lock.yaml
bump version of `postcss-plugin-rpx2vw` (latest 1.0.0)
> chore: update version of postcss plugin

- packages/runtime/src/appConfig.ts
Strict Mode 是用于标记应用中潜在的代码问题。比如：
1. 识别出过时的生命周期、API（ref、context）、方法
2. 检测副作用（数据请求、数据订阅、修改 DOM 等），开启严格模式后会在 dev 阶段下会调用 effect 两次
- 为什么要检查副作用？concurrent 模式下可能会多次调用 render 阶段的生命周期方法后，才到 commit 阶段。调用 effect 两次是为了在 dev 阶段能帮助开发者发现内存泄露、无效应用状态等问题
- 如果尽量少写副作用？事件回调；getData；react-query；
建议默认不开启。原因有：
- 大部分开发者不知道为什么 effect 回调函数会调用两次，代码中也没有显式声明是启用 strict mode，减少认知成本
-Strict Mode 属于高级特性
- 一般上用到的流行的组件库，不会用过期的 API 或生命周期。并且我们文档有推荐数据请求的正确姿势
但文档上标明 推荐开启。
参考文档：
- https://react.docschina.org/docs/strict-mode.html
- https://segmentfault.com/a/1190000042059978
- https://segmentfault.com/a/1190000041942007
> chore: set app.strict default value to false

- packages/ice/src/service/serverCompiler.ts
- packages/types/src/config.ts
支持在插件中修改 server 端的构建配置。
```ts
onGetConfig(config => {
config.server = config.server || {};
config.server = {
buildOptions: {
xxxx
}
}
})
```
> feat: support pass server build options

- packages/ice/src/service/serverCompiler.ts
deepmerge 操作会改变  task.config?.server?.buildOptions 的值，导致该对象可能包含上次 serverCompiler 的入参`originBuildOptions` 的值
> fix: merge buildOptions

- packages/ice/bin/ice-cli.mjs
- packages/ice/src/createService.ts
- packages/ice/src/utils/runtimeEnv.ts
在插件 (faas 插件) 加载的时候，拿到 process.env.NODE_ENV 的值是 undefined
> fix: can not get the NODE_ENV value in plugin

- packages/ice/src/routes.ts
Fix: replace dash of route id when generate template
> fix: replace dash of route id when generate template

- packages/types/src/config.ts
- packages/webpack-config/src/getCompilerPlugins.ts
支持以下方式区分 server 构建逻辑：
```js
import { defineConfig } from '@ice/app';
export default defineConfig({
transform: (code, id, { isServer }) => {
if (isServer) {
console.log('server');
}
return code;
},
});
```
> feat: pass server option to config transform

- packages/runtime/src/runServerApp.tsx
- packages/runtime/src/server/streamRender.tsx
- 去掉 `abort()`，避免循环调用 `onError` 回调导致栈溢出
- 添加 disableFallback 参数，支持把错误交给方法调用时处理
> fix: ssr stream error recursion

- packages/webpack-config/src/getCompilerPlugins.ts
re-order the transform plugins, so we can get the source code in user config `transform`
> fix: the order of transform plugins

- packages/ice/src/service/preBundleCJSDeps.ts
需要兼容类似 [lodash.debounce](https://unpkg.com/browse/lodash.debounce@4.0.8/) 包没有在 package.json 中指明入口，默认是根目录的 index.js
> fix: no main entryPoint

- packages/ice/src/service/analyze.ts
- packages/ice/tests/preAnalyze.test.ts
`/.(j|t)s(x)?$/` => `/\.(j|t)s(x)?$/`
> fix: regex error for resolve aliased path

- packages/webpack-config/src/getCompilerPlugins.ts
umd of react-router and react-router-dom contains `const`, so it need to be compiled
> fix: compile react-router and react-router-dom

- packages/runtime/src/runServerApp.tsx
服务端渲染时没有取到设定的 serverOnlyBasename 进行 Router 匹配
> fix: incorrect server render basename

- packages/runtime/src/runClientApp.tsx
csr 的时候，不应该拿 serverOnlyBasename 作为 basename 进行路由匹配
> fix: render client app basename

- packages/runtime/src/types.ts
移除 AppConfig 继承的索引类型，避免在写 appConfig 时没有类型报错信息
> chore: remove AppConfig extends index type

- packages/rax-compat/src/create-element.ts
兼容 rax-components 中通过 useImperativeHandle 对 ref 进行自定义导致无法访问正确的 eventTarget 的情况。
> fix: should get eventTarget by _nativeNode

- constants.ts
这个数组之前是用于本地调试（npm run watch）的时候 ice-pkg 的包使用单独构建，其他使用 tsc 构建。现在统一走 pnpm monorepo 构建，故此文件没用了
> chore: remove unused constants.ts

- packages/style-import/src/index.ts
处理组件名称未转换为短横线式，导致引入样式异常问题
统一在 style-import 中将名称转换为短横线式，增加了 toKebab 参数来控制是否对名称进行转换，默认开启
> fix: transform component name

- packages/ice/src/constant.ts
- packages/ice/tests/preBundleCJSDeps.test.ts
- packages/ice/tests/transformImport.test.ts
cache 目录统一在 node_modules/.cache 下
before:
after:
> chore: unite cache dir

- packages/plugin-store/package.json
- packages/plugin-store/src/api.ts
- packages/plugin-store/src/index.ts
- packages/plugin-store/src/runtime.tsx
导致这个问题的出现是因为循环依赖导致的。推荐后面如果要从插件中导出 api，最后是在一个单独的文件导出，而不是从 runtime 中导出
> fix: can not read store api from ice

- examples/basic-project/package.json
- examples/csr-project/package.json
- examples/hash-router/package.json
- examples/rax-project/package.json
- examples/routes-generate/package.json
- examples/with-antd-mobile/package.json
- examples/with-antd/package.json
- examples/with-fusion/package.json
- examples/with-pha/package.json
- examples/with-store/package.json
- packages/ice/package.json
- packages/ice/src/createService.ts
- packages/webpack-config/package.json
- packages/webpack-config/src/unPlugins/compilation.ts
- pnpm-lock.yaml
Config `regenerator.importPath` is not supported by @swc/core (while @builder/swc is supported), use absolute alias path for `regenerate-runtime`.
> fix: lock regenerate-runtime path

- packages/ice/src/routes.ts
generate `data-loader` when getData only export in nested routes
> fix: nested routes of which getData

- packages/ice/src/utils/babelPluginRemoveCode.ts
- packages/ice/tests/fixtures/removeCode/expression.ts
- packages/ice/tests/removeTopLevelCode.test.ts
fix remove case of `ExpressionStatement`
> fix: remove code of top level expression

- packages/ice/src/middlewares/ssr/renderMiddleware.ts
- packages/ice/src/service/webpackCompiler.ts
- fix: 当没有根路由时，dev 的时候访问页面时报 404 的错误
- fix: 开启 hash 路由时，在控制台打印的 URL 没有带上 # 字符
> fix: hash router fail when no index route

- examples/basic-project/src/pages/index.tsx
- packages/ice/package.json
- packages/types/package.json
- packages/webpack-config/package.json
- packages/webpack-config/src/unPlugins/compilation.ts
- pnpm-lock.yaml
This PR(https://github.com/unjs/unplugin/pull/161) has  fixed the type error.
> chore: upgrade unplugin version to fix sourcemap type

- packages/plugin-rax-compat/src/index.ts
> fix: fix error when test is a function

- packages/ice/src/config.ts
- packages/ice/src/createService.ts
- packages/webpack-config/src/unPlugins/compilation.ts
- `loose: true` may cause some unexpected compilation, such as `for...of`
- fix default value of `compileDependencies`
> fix: default value of compilation

- tests/integration/app-config.test.ts
- tests/integration/basic-project.test.ts
- tests/integration/routes-generate.test.ts
- tests/utils/browser.ts
- tests/utils/build.ts
- tests/utils/start.ts
在 windows CI 环境下，有可能出现 routes-generate 的单测用例超时的情况，目前优化减少 setupBrowser 的次数
https://github.com/ice-lab/ice-next/actions/runs/3065194845/jobs/4949054085
> test: fix routes-generate unit test timeout

- packages/runtime/src/Document.tsx
- packages/runtime/src/runClientApp.tsx
- packages/runtime/src/runServerApp.tsx
- packages/types/src/runtime.ts
当 SSR 降到到 CSR 时，Client 端同时切换 hydrate 为 render
> fix: disable hydrate when downgrade

- pnpm-lock.yaml
- website/docs/guide/plugins/store.md
- website/docusaurus.config.js
- website/package.json
顺带修复了 diff 语法不高亮的问题（是配置的主题引起的）
> docs: store

- examples/app-config/src/typings.d.ts
- examples/app-config/tsconfig.json
- examples/basic-project/src/pages/about.tsx
- examples/basic-project/src/typings.d.ts
- examples/basic-project/tsconfig.json
- examples/csr-project/src/typings.d.ts
- examples/csr-project/tsconfig.json
- examples/rax-inline-style/src/typings.d.ts
- examples/rax-inline-style/tsconfig.json
- examples/rax-project/src/typings.d.ts
- examples/rax-project/tsconfig.json
- examples/with-antd-mobile/src/typings.d.ts
- examples/with-antd-mobile/tsconfig.json
- examples/with-antd/src/typings.d.ts
- examples/with-antd/tsconfig.json
- examples/with-fusion/src/typings.d.ts
- examples/with-fusion/tsconfig.json
- examples/with-pha/src/typings.d.ts
- examples/with-pha/tsconfig.json
- examples/with-plugin-request/src/typings.d.ts
- examples/with-plugin-request/tsconfig.json
- packages/ice/package.json
- packages/ice/types.d.ts
增加框架内置的 TS 类型提示，比如：
- CSS Modules
- 图片、字体、媒体等文件
- web worker
- 环境变量（process.env.xxx）
用户模板只需要在 src/typings.d.ts 中引入以下代码即可：
```ts
/// <reference path="@ice/app/types" />
```
> feat: enhance framework types

- examples/basic-project/src/pages/about.tsx
- examples/basic-project/src/pages/blog.tsx
- examples/with-pha/src/pages/home.tsx
- packages/ice/src/createService.ts
- packages/ice/src/service/runtimeGenerator.ts
- packages/ice/templates/core/env.server.ts.ejs
- packages/ice/templates/core/index.ts.ejs
- packages/ice/templates/core/types.ts.ejs
- packages/plugin-auth/src/index.ts
- packages/plugin-auth/src/types.ts
- packages/plugin-pha/src/index.ts
- packages/runtime/src/RouteContext.ts
- packages/runtime/src/routesConfig.ts
- packages/types/src/generator.ts
- packages/types/src/plugin.ts
- packages/types/src/runtime.ts
> feat: support route config type

- examples/with-plugin-request/ice.config.mts
- examples/with-plugin-request/src/app.tsx
- packages/ice/templates/core/entry.client.ts.ejs
- packages/ice/templates/core/entry.server.ts.ejs
- packages/ice/templates/core/runtimeModules.ts.ejs
- packages/miniapp-runtime/src/app/runClientApp.tsx
- packages/plugin-request/src/index.ts
- packages/runtime/src/routesConfig.ts
- packages/runtime/src/runClientApp.tsx
- packages/runtime/src/runServerApp.tsx
- packages/runtime/src/runtime.tsx
- packages/runtime/tests/runClientApp.test.tsx
- packages/runtime/tests/runServerApp.test.tsx
- packages/types/src/runtime.ts
`statc runtime` 说明：
对于一些支持在 src/app 入口就可以使用的 API，如 request 的运行时能力，需要在应用数据 / 路由数据加载获取前就需要加载，否则在 getAppData 中将无法享受到统一的配置能力
Close #604 #605
> feat: support static runtime

- website/docs/guide/advanced/antd.md
- website/docs/guide/advanced/fusion.md
- website/docs/guide/plugins/plugin-list.md
Add docs for `@ice/plugin-antd` and `@ice/plugin-fusion`
> docs: plugin antd and fusion

- packages/webpack-config/src/webpackPlugins/AssetsManifestPlugin.ts
Fix error when assets manifest add to css file.
> fix: add assets manifest only in js file

- website/docs/guide/basic/mock.md
> docs: mock use middleware

- packages/runtime/src/dataLoader.ts
fix: https://github.com/ice-lab/ice-next/issues/615
> fix: load data without matched ids

- packages/ice/templates/core/entry.client.tsx.ejs
- packages/runtime/src/Document.tsx
- packages/webpack-config/src/index.ts
- tests/integration/basic-project.test.ts
Fix #630
- 模版入口中增加 react 组件写法，确保 jsx-runtime 在入口已被依赖，原因是 entry 不依赖任何组件的情况下 @ice/jsx-runtime 将会在路由组件 chunk 中打包，导致额外依赖 framework
- 增加重复脚本输出的过滤，确保异常 case 的重复 chunk
> fix: duplicate assets in document output

- packages/webpack-config/package.json
- packages/webpack-config/src/config/css.ts
- packages/webpack-config/src/index.ts
- packages/webpack-config/src/types.ts
- pnpm-lock.yaml
#634 
1. swc 和 postcss-preset-env 默认会读取项目的 .browserslistrc 和 package.json 中的 browserslist 配置作为目标浏览器，框架默认就不处理 browserslist 的配置，都交给对应的 compiler 做处理好了。故此 PR 去掉
2. 推荐主流浏览器版本，默认写在模板的 .browserslist
> feat: read browsers config by postcss-preset-env

- examples/with-plugin-request/ice.config.mts
- packages/ice/src/plugins/web/index.ts
- packages/ice/src/types/plugin.ts
- packages/ice/src/webpack/DataLoaderPlugin.ts
- packages/ice/templates/exports/data-loader.ts.ejs
- packages/plugin-request/src/index.ts
- packages/runtime/src/dataLoader.ts
- packages/runtime/src/types.ts
fix: https://github.com/ice-lab/ice-next/issues/600
> fix: request in data loader

- examples/with-data-loader/src/pages/home.tsx
- packages/ice/templates/exports/data-loader.ts.ejs
- packages/runtime/src/AppData.tsx
- packages/runtime/src/RouteContext.ts
- packages/runtime/src/dataLoader.ts
- packages/runtime/src/dataLoaderFetcher.ts
- packages/runtime/src/index.ts
- packages/runtime/src/routes.tsx
- packages/runtime/src/runClientApp.tsx
- packages/runtime/tests/routes.test.tsx
- packages/runtime/tests/runClientApp.test.tsx
- tests/integration/basic-project.test.ts
- dataLoader.ts 文件中只保留了 CSR 时，初始化数据请求的逻辑，避免增加太多的环境判断，及透传不同环境下 context 的问题
- 在 data-loader.js 和常规的数据请求中，各增加了对静态配置的判断
- 修复 data-loader.js 构建了 react 的问题
> refactor: data loader
